set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=default,fg=#565f89'
set -g status-left-length 40
set -g status-right-length 160

set -g status-left '#[fg=#{?client_prefix,#ff9e64,#{?pane_in_mode,#bb9af7,#{?pane_synchronized,#f7768e,#a6e22e}}}]#S   '

set -g window-status-separator ' '
set -g window-status-format ' #(tmux-pane-breath-status "#{pane_tty}") #[fg=#{?window_bell_flag,#f7768e,#{?window_activity_flag,#7a82a8,#4b5263}}]#{?window_zoomed_flag,#[italics],}#{window_name}#[noitalics] '
set -g window-status-current-format '#[fg=#16181f]#[bg=#16181f]#(tmux-pane-breath-status "#{pane_tty}" current) #[fg=#a9b1d6]#{?window_zoomed_flag,#[italics],}#{window_name}#[noitalics]#[bg=default]#[fg=#16181f]'

set -g message-style 'bg=#16181f,fg=#a9b1d6'
set -g message-command-style 'bg=#16181f,fg=#a6e22e'
set -g mode-style 'bg=#283457,fg=#c0caf5'
set -g pane-border-style 'fg=#1a1d26'
set -g pane-active-border-style 'fg=#3b4048'
set -g display-panes-active-colour '#a6e22e'
set -g display-panes-colour '#4b5263'
setw -g clock-mode-colour '#a6e22e'
