unbind r
bind r source-file ~/.config/tmux/tmux.conf

set-option -ga terminal-overrides ",*256col*:Tc:RGB"
set -g default-terminal "xterm-256color"

setw -g pane-base-index 200
set -g base-index 100


set-window-option -g mode-keys vi
set -g window-status-separator ''
set -g window-status-format "#W"
set -g window-status-current-format "#W"
set -g status-interval 5
set -g display-time 4000

setw -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

setw -g aggressive-resize off
setw -g clock-mode-style 24
set -s escape-time 500
set -g history-limit 1000000

set -g @lsyncd_status_file '/tmp/lsyncd.status'

set -g status-right '#(tmux-lsyncd-status) #(gitmux -cfg $HOME/.config/gitmux.conf "#{pane_current_path}")'
