unbind r
bind r source-file ~/.config/tmux/tmux.conf

set-option -ga terminal-overrides ",*256col*:Tc:RGB"
set -g default-terminal "xterm-256color"

setw -g pane-base-index 0
set -g base-index 100

set-window-option -g mode-keys vi
set -g window-status-separator ' | '
set -g status-left ''

set -g status-interval 1
set -g window-status-format '#(tmux-pane-breath-status "#{pane_tty}" "#{window_name}")'
set -g window-status-current-format '#(tmux-pane-breath-status "#{pane_tty}" "#{window_name}" current)'

set -g pane-border-status off
set -g display-time 4000

setw -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

setw -g aggressive-resize off
setw -g clock-mode-style 24
set -s escape-time 500
set -g history-limit 1000000

set -g @lsyncd_status_file '/tmp/lsyncd.status'

set -g update-environment "SSH_AUTH_SOCK SSH_AGENT_PID"

set -g status-right '#(tmux-gpg-agent-status) #(tmux-ssh-agent-status) #(tmux-lsyncd-status) #(gitmux -cfg $HOME/.config/gitmux.conf "#{pane_current_path}")'
