{
  imports = [
    ./components/alacritty
    ./components/btop
    ./components/lazygit
    ./components/macchina
    ./components/tmux
    ./components/zsh
    ./components/bat.nix
    ./components/direnv.nix
    ./components/eza.nix
    ./components/fzf.nix
    ./components/ghostty.nix
    ./components/git.nix
    ./components/magic-wormhole.nix
    ./components/starship.nix
    ./components/zoxide.nix
  ];
}
